import_from_git(url: 'https://github.com/Digipolitan/fastlane-common')
import_from_git(url: 'https://github.com/Digipolitan/fastlane-ios')
import_from_git(url: 'https://github.com/Digipolitan/fastlane-ios-framework')
import_from_git(url: 'https://github.com/Digipolitan/fastlane-ios-ci-framework')
